### ISSUE TITLE
Не закрывается соединение с RAbbitMQ при ошибке

### ISSUE THREAD

**Issue by tarampampam** [avto-dev/amqp-rabbit-laravel-queue#15]
Заметил, что в случае, когда успешно запустить воркера не удается ("что-то пошло не так при запуске"), RabbitMQ сообщает о неверном количестве consumers (фактически их может быть лишь 3, когда отображается 15).

С таким сталкивался при деплое приложения, что использует данный пакет, на swarm (так как отсутствует `depends_on` и проверка на доступность порта контейнера с RabbitMQ - часть попыток запуска процессов `./artisan queue:work` завершается ошибкой при запуске).

Есть ощущение, что это связано с тем, что отсутствует `try ... catch` в классе воркера - https://github.com/avto-dev/amqp-rabbit-laravel-queue/blob/master/src/Worker.php (возможно это не так), но ты уже сообщал о подобном поведении, поэтому и предлагаю тебе разобраться детальнее с этой проблемой.

**Comment by Reallife** [comment]
@tarampampam
Пока проблему не удалось воспроизвести. Ни локально, ни под `docker swarm`. Были
- попытки выбрасывать исключения на различных этапах работы воркера
- попытки убивать контейнер(`docker kill`) во время обработки сообщения из очереди 
- попытки запустить консамера до того, как будут созданы необходимые очереди

Зомби-консамеров отловить не удалось. 

Да, я сталкивался с такой ситуацией, на тот момент причину выяснить так и не удалось, а возникала она достаточно редко. В последствии оказалось, что такой эффект могли давать `Standalone` контейнеры в ранчере, которые оставались после удаления стека. Пару раз ловил именно эту причину. После удаления таких контейнеров число консамеров на очереди приходило в норму. 

Проблему держу в голове, периодически буду экспериментировать с попытками воспроизвести её. Предлагаю вернуться к этой проблеме через некоторое время.

**Comment by tarampampam** [comment]
Принято. Откроем isuue после успешного воспроизведения
