### ISSUE TITLE
PHP 8 in composer

### ISSUE THREAD

**Issue by panki3a** [avto-dev/amqp-rabbit-laravel-queue#21]
Hi,
Is it possible to release new version of this package with php 8.0|8.1 support in composer?

Thank you.

**Comment by eldario** [comment]
@panki3a 

The only problem was that the package [php-amqp](https://github.com/php-amqp/php-amqp) - did not support version `php8`.
From the new version, it seems, there is support, but such an [issue](https://github.com/php-amqp/php-amqp/issues/411) was found. 

We will try.

**Comment by panki3a** [comment]
But there is new version 1.11.0 https://pecl.php.net/package/amqp/1.11.0, which support php 8.1, and it is stable

**Comment by panki3a** [comment]
@eldario in comment, there is info, that its working.
https://github.com/php-amqp/php-amqp/issues/411#issuecomment-1019967491

**Comment by eldario** [comment]
@panki3a 

Hello

Can you pull changes from branch `dev-support-php-8` from #22 ?

You need to modify `composer.json`, for example

```
...
        "avto-dev/amqp-rabbit-laravel-queue": "dev-support-php-8",
        "avto-dev/amqp-rabbit-manager": "dev-support-php-8",
        "enqueue/amqp-ext": "^0.10",
...
```

**Comment by panki3a** [comment]
I will look at this and send you info

**Comment by eldario** [comment]
@panki3a 
Any progress in testing?
