### ISSUE TITLE
How can I get the id of a job?

### ISSUE THREAD

**Issue by Bariskau** [avto-dev/amqp-rabbit-laravel-queue#30]
I am developing a **job tracker** to keep track of jobs in the queue. This tracker needs to create a record** when the job completes **successfully** or **failed**.

**As a result,** what I want to do is if a job fails, write the id of this job to the database and try again manually.

> CallWebhookJob.php
```php
<?php

namespace App\Jobs;

use AvtoDev\AmqpRabbitLaravelQueue\HasPriorityTrait;

class CallWebhookJob extends \Spatie\WebhookServer\CallWebhookJob
{
    use HasPriorityTrait;

    /**
     * Create a new job instance.
     *
     * @return void
     */
    public function __construct()
    {
    }

    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        parent::handle();
        info([
            "job_id" => $this->job->getJobId()
        ]);
    }

}
```

> Job id information in the log file:
```
[2023-02-01 18:48:37] local.INFO: array (
  'job_id' => 'job-095adf5b',
)  
```

There is no problem until here. The library continues the process by giving a random id for messages. In rabbitmq message details, the randomly generated id appears as expected.

But if the rabbitmq.php config file is configured as follows and the failed field in the queue config is set to rabbitmq instead of database. While the job is waiting in the queue, there is no problem again. But if the job is written to the failed_jobs queue after it fails, rabbitmq has to change the message id. And I cannot follow that job.

> rabbitmq.php
```php
<?php

use Interop\Amqp\AmqpQueue;
use Interop\Amqp\AmqpTopic;

return [
    'connections' => [
        'rabbit-default' => [
            'host'  => env('RABBIT_HOST', '0.0.0.0'),
            'port'  => (int) env('RABBIT_PORT', 5672),
            'vhost' => env('RABBIT_VHOST', '/'),
            'user'  => env('RABBIT_LOGIN', 'guest'),
            'pass'  => env('RABBIT_PASSWORD', 'guest'),
        ],
    ],

    'default_connection' => 'rabbit-default',

    'queues' => [
        'jobs' => [
            'name'         => env('JOBS_QUEUE_NAME', 'jobs'),
            'flags'        => AmqpQueue::FLAG_DURABLE,
            'arguments'    => [
                'x-max-priority' => 255,
            ],
            'consumer_tag' => null,
        ],

        'failed' => [
            'name'         => env('FAILED_JOBS_QUEUE_NAME', 'failed-jobs'),
            'flags'        => AmqpQueue::FLAG_DURABLE,
            'arguments'    => [
                'x-message-ttl' => 604800000,
                'x-queue-mode'  => 'lazy',
            ],
            'consumer_tag' => null,
        ],
    ],

    'exchanges' => [

        'delayed-jobs' => [
            'name'      => env('DELAYED_JOBS_EXCHANGE_NAME', 'jobs.delayed'),
            'type'      => 'x-delayed-message',
            'flags'     => AmqpTopic::FLAG_DURABLE,
            'arguments' => [
                'x-delayed-type' => AmqpTopic::TYPE_DIRECT,
            ],
        ],

    ],

    'setup' => [
        'rabbit-default' => [
            'queues'    => [
                'jobs',
                'failed',
            ],
            'exchanges' => [
                'delayed-jobs',
            ],
        ],
    ],
];
```

> queue.php
```php
<?php

use AvtoDev\AmqpRabbitLaravelQueue\Connector;

return [

    'connections' => [

        'rabbitmq' => [
            'driver'              => Connector::NAME,
            'connection'          => 'rabbit-default',
            'queue_id'            => 'jobs',
            'delayed_exchange_id' => 'delayed-jobs',
            'timeout'             => (int)env('QUEUE_TIMEOUT', 0), // The timeout is in milliseconds
            'resume'              => (bool)env('QUEUE_RESUME', false), // Resume consuming when timeout is over
            'worker'              => env('RABBITMQ_WORKER', 'default'),
        ],

    ],


     // Message id is changing
    'failed' => [
        'connection' => 'rabbit-default',
        'queue_id'   => 'failed',
    ],

    // Message id is not changing
    'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],

];
```

**Comment by eldario** [comment]
Thanks for the question.

_I'm afraid I misunderstood._

What about this usage;

```php
$this->job->getJobId() 
```
This is the identifier used to send the message to the queue.

#### Example

![изображение](https://user-images.githubusercontent.com/6119929/216063937-85f54e83-d0fd-411d-b711-e36774a94ae8.png)

## Additional information

The Laravel framework has a functionality that is responsible for viewing failed jobs.

### List all failed jobs
```
php artisan queue:failed 
```

### Result:
![изображение](https://user-images.githubusercontent.com/6119929/216062022-a271744c-498a-421b-a39e-61e2fa6204d4.png)

### Retry failed job
```
$ php artisan queue:retry e5c2198e-65aa-4e21-a0b4-ed56695ef04b
```
### Result
```sh
The failed job [e5c2198e-65aa-4e21-a0b4-ed56695ef04b] has been pushed back onto the queue!
```

In order for this functionality to work, it is enough to write the following
### `config/queue.php`
```php
...
   'failed' => [
        'driver'      => 'database-uuids', // remove it if you want to use `ID` insteadof `UUID`
        'database'    => 'pgsql', // use your connection name
        'table'       => 'failed_jobs',
    ],
...

```

**Comment by Bariskau** [comment]
@eldario First of all, the library is admirable. Thank you for all your hard work. I solved my problem the way you mentioned. But my aim was to use rabbitmq queue instead of failed_jobs table. 

Also, I coded a connector to work with horizon worker if anyone needs it. I will open pr after testing.

**Comment by eldario** [comment]
@Bariskau 

Have you tried specifying these values in the config?
Full view for `ServiceProvider.php` -> [source](https://github.com/avto-dev/amqp-rabbit-laravel-queue/blob/master/src/ServiceProvider.php#L67)
### `config/queue.php`

```php
...
   'failed' => [
        'connection'  => 'rabbitmq', // put here real connection key
        'queue_id'    => 'jobs-failed', // put here real name of failed queue 
    ],
...
```

**Comment by eldario** [comment]
@Bariskau 
Returning to the discussion, it is enough to specify in the config

### `config/queue.php`
```php
...
   'failed' => [
        'database'    => 'pgsql', // use your connection name
        'table'       => 'failed_jobs',
    ],
...
```

Next use the command
```sh
$ php artisan queue:failed
```

**Comment by eldario** [comment]
@Bariskau

1. To manage failed jobs manually, you need to store this information somewhere

```
...
   'failed' => [
        'database'    => 'pgsql', // use your connection name
        'table'       => 'failed_jobs',
    ],
...
```
2. if you use a `rabbitmq` for failed jobs, they will be moved to another queue and executed.
3. You may listen `JobFailed` event, and try to store serialize model of `$job_failed_event->job`

**Comment by Bariskau** [comment]
@eldario Thank you for your help. Using **database driver** for failed jobs met my need. 

```php
   'failed' => [
        'driver' => env('QUEUE_FAILED_DRIVER', 'database-uuids'),
        'database' => env('DB_CONNECTION', 'mysql'),
        'table' => 'failed_jobs',
    ],
```
