### ISSUE TITLE
Dispatching a job with a different queue

### ISSUE THREAD

**Issue by Bariskau** [avto-dev/amqp-rabbit-laravel-queue#31]
When I dispatch a job using different **queue names**, it is always processed with the same queue.

> Ex:
```php
// queue name jobs
dispatch(new DemoJob())->onQueue("jobs");
// queue name other_jobs
dispatch(new DemoJob())->onQueue("other_jobs");
```

> ### Expected behaviour:
> When the above code is executed, there should be 1 DemoJob in `jobs` and `other_jobs` queues. 
> ### Actual behaviour:
> There are 2 jobs in `jobs` queue. `other_jobs` queue is empty.

**queue.php**
Whatever the **queue_id** value is, the package sends jobs to that queue.
```php
 'rabbitmq' => [
            'driver'              => Connector::NAME,
            'connection'          => 'rabbit-default',
            'queue_id'            => 'jobs',
            'delayed_exchange_id' => 'delayed-jobs',
            'timeout'             => (int) env('QUEUE_TIMEOUT', 0), // The timeout is in milliseconds
            'resume'              => (bool) env('QUEUE_RESUME', false), // Resume consuming when timeout is over
            'worker' => env('RABBITMQ_WORKER', 'default'),
        ]
```
**rabbitmq.php**
```php
   // ...
  'queues' => [
        'jobs' => [
            'name'         => env('JOBS_QUEUE_NAME', 'jobs'),
            'flags'        => AmqpQueue::FLAG_DURABLE,
            'arguments'    => [
                'x-max-priority' => 255,
            ],
            'consumer_tag' => null,
        ],

        'other_jobs' => [
            'name'         => env('JOBS_QUEUE_NAME', 'other_jobs'),
            'flags'        => AmqpQueue::FLAG_DURABLE,
            'arguments'    => [
                'x-max-priority' => 255,
            ],
            'consumer_tag' => null,
        ],
    ]
```

**Comment by eldario** [comment]
Hello @Bariskau 

If you want to split tasks into `queues`, try creating a new `connection`

## `config/queue.php`

```php
 'connections' => [
        'connection-first-rabbitmq' => [
            'driver'              => Connector::NAME,
            'connection'          => 'rabbit-default',
            'queue_id'            => 'jobs',
            'delayed_exchange_id' => 'delayed-jobs',
            'timeout'             => (int) env('QUEUE_TIMEOUT', 0), // The timeout is in milliseconds
            'resume'              => (bool) env('QUEUE_RESUME', false), // Resume consuming when timeout is over
            'worker'              => env('RABBITMQ_WORKER', 'default'),
        ],

        'connection-second-rabbitmq' => [
            'driver'              => Connector::NAME,
            'connection'          => 'rabbit-default',
            'queue_id'            => 'other_jobs',
            'delayed_exchange_id' => 'delayed-jobs',
            'timeout'             => (int) env('QUEUE_TIMEOUT', 0), // The timeout is in milliseconds
            'resume'              => (bool) env('QUEUE_RESUME', false), // Resume consuming when timeout is over
            'worker'              => env('RABBITMQ_WORKER', 'default'),
        ],
    ]
````

And the task is already running on behalf of the connection
## `someFile.php`

```php
// queue name jobs
dispatch(new DemoJob())->onConnection("jobs");

// queue name other_jobs
dispatch(new DemoJob())->onConnection("other_jobs");
```

**Comment by Bariskau** [comment]
@eldario Hi, 
Yes, I have tried such a method myself, but I don't think it can be very logical. 

Here, sending the queue object as an array may be a **better** solution.
https://github.com/avto-dev/amqp-rabbit-laravel-queue/blob/ba93b0a790eb74c3ca2ce5aa60927e9b1bd7be6f/src/Connector.php#L80

connector.php
```php
 public function connect(array $config): QueueContract
    {
        $queueConfig = $this->container->make(ConfigRepository::class)->get('rabbitmq.queues');


        $queues = [];
        foreach ($queueConfig as $queueId => $queue) {
            $queues[$queueId] = $this->connections->make($queueId);
        }
        
        // ...
    }


```

**Comment by eldario** [comment]
@Bariskau 

I may be **misunderstanding**, but I will **suggest**


This **package** will not be able to do this, because the configuration for the queue serves both:
- to send a message to the queue
- to create a consumer to process incoming messages.


---

I can suggest the following **solutions**

### First

Create a new **connection** with a different name for the queue and exchange.

In this way, you can distribute the load, for example
The first queue will be serviced by **10 consumers**, the second queue will be serviced by **2 consumers**.
You get 2 independent processes.

### Second

The second solution looks like transferring responsibility from the **application** to the **broker**.

Use the method of sending messages not to a queue, but to an **exchange**, using `->setRoutingKey()` and using this to distribute tasks among queues

**Comment by eldario** [comment]
@Bariskau 

What's up with this **issue**?

**Comment by Bariskau** [comment]
@eldario Thank you for your answer. I opened multiple connections and each worker uses a different connection. It's ok for me.
